[package]
name = "any-of-tree-sitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-rust = "0.20.4"
tree-sitter = "~0.20.10"

[build-dependencies]
cc="*"

